### ISSUE TITLE
Getting Error 401 on iOS and Windows 10 

### ISSUE THREAD

**Issue by Mike-b07e5** [chhoumann/quickadd#475] opened 2023-04-25 18:12 UTC
**Describe the bug**
When I attempt to execute an AI macro on iOS or Windows 10, I get an error 401.  It DOES work on iPadOS

**To Reproduce**
I followed normal install procedures
I set up the defaults
I created the Manual Prompt.md file 
I created a blank file and ran the macro.
The macro accepts my input then comes back with an error 401.

**Expected behavior**
I thought it would execute my prompt with GPT.  Instead it gave an error 401.

**Screenshots**
not currently available

**Desktop (please complete the following information):**
 - OS: Windows 10 AND iOS
 - working from Obsidian
 - Latest as of today

**Additional context**
As mentioned, the same setup (same vault) works on iPad.  I confirmed exact same setup between iOS and iPad.

**Comment by chhoumann** [comment] 2023-04-25 18:59
Hey @Mike-b07e5, thanks for reporting this!

401 means unauthorized. It might be the case that the key wasn't synchronized properly. Could you try updating the setting manually on your computer to force a save update? Adding and removing a space should be fine.

Let me know if this works :)

**Comment by Mike-b07e5** [comment] 2023-04-25 20:52
It does not allow me to update.  The key field says sk...  and I cannot edit it.

**Comment by chhoumann** [comment] 2023-04-25 20:57
Ah, so if it says that, you're seeing the placeholder value, indicating the field is empty. 

Are you able to write anything in the field or no?

**Comment by Mike-b07e5** [comment] 2023-04-25 21:05
Actually, that was from my Windows machine.  I was able to edit the field on iPad.  Removed and re-added the last character. The Assistant still works for iPad, and still doesn't work with iOS and Windows.

**Comment by Mike-b07e5** [comment] 2023-04-25 21:19
I was able to edit iOS and it is now working.  Rechecking the others...

**Comment by Mike-b07e5** [comment] 2023-04-25 21:24
Well, turns out I can edit the key in iOS and Windows (not sure what my fail was).
It is now working on all 3 devices.

**Comment by chhoumann** [comment] 2023-05-06 09:34
Hey @Mike-b07e5, thanks for getting back to me on this. Looks like it was some kind of API key sync issue.

I think I have an idea what the root cause is, but it's not 100% in QuickAdds control. Will see what I can do, but closing this issue for now.

**Closed by chhoumann** 2023-05-06 09:34 UTC
Labels: bug
